version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: slimphp_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www
      - /var/www/vendor  # Don't mount vendor directory to avoid permission issues
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: slim_tasks
      DB_USERNAME: postgres
      DB_PASSWORD: password
      API_KEYS: 427bb67d-07f8-4220-a11a-7dfb181e9bdc,ea7853e9-0a36-4b21-beac-860fc94d9680

  db:
    image: postgres:15
    container_name: slimphp_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: slim_tasks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
